### ISSUE TITLE
Bitbucket Server 4.6 issues

### ISSUE THREAD

**Issue by danofthewired** [danofthewired/puppet-bitbucket#21]
New scripts now exist to set the RunAs user and home directory as well as the addition of local and remote elastic search. Currently the module doesn't fully support Bitbucket version 4.6+.

**Comment by optiz0r** [comment]
I'm in the process of preparing a PR to add support for 4.6 (with local elastic search), will have it with you later today. Rather than modify the set-bitbucket-user.sh script (which I've seen other people do, in spite of the big do-not-edit warning at the top of the file), the direction I took was to make the redhat init script do the user switching, more like the debian init script does.

**Comment by danofthewired** [comment]
Thanks for the updates. Don't work too hard! Closing this issue as the code you supplied fixed the issue.
