### ISSUE TITLE
bundled Elasticsearch issues

### ISSUE THREAD

**Issue by claflico** [danofthewired/puppet-bitbucket#25]
The newer versions of bitbucket have elasticsearch bundled with it for code searches and such but after setting up bitbucket using this module the elasticsearch service isn't running. When I try to start the service manually I get an error message about BITBUCKET_HOME not being set.

**Comment by danofthewired** [comment]
This is due to the newer version of Bitbucket changing the bash script used for sourcing the HOME environment variable. I have created a new version of the Bitbucket module on PuppetForge which supports this by setting the variables used for bitbucket home and user in the bitbucket init script. Otherwise you can update the script in /bin/set-bitbucket-home.sh and /bin/set-bitbucket-user.sh manually to solve the issue.

**Comment by claflico** [comment]
Just an fyi, this is the version I'm using:
mod 'thewired/bitbucket', '2.1.0'
